[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-login>=0.6.3",
    "oauthlib>=3.2.2",
    "twilio>=9.4.5",
]
