[package]
name = "uwu_bot"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serenity = { version = "0.11", features = ["client", "framework"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"

[build-dependencies]
walkdir = "2.5"